services:
  - type: web
    name: smartseason-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        value: smartseason-jwt-secret-2024
      - key: PORT
        value: 10000
    healthCheckPath: /health
